name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Formatting
        run: poetry run black . --check

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: project.settings
          SECRETS_FILE: .confidential/ci.json
        run: poetry run pytest --cov . -n 2